# Generated by Django 4.2.3 on 2023-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.BigIntegerField(unique=True)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=64, null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('imported_t', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('imported', 'Imported'), ('draft', 'Draft')],
                        default='draft',
                        max_length=8,
                    ),
                ),
                ('brands', models.ManyToManyField(to='products.brand')),
                ('categories', models.ManyToManyField(to='products.category')),
                ('packaging', models.ManyToManyField(to='products.packaging')),
            ],
        ),
    ]
